--1. 테이블 생성
CREATE TABLE ENROLMENT(
    JAVA VARCHAR2(30),
    ORACLE VARCHAR(30),
    JSP VARCHAR(30),
    SERVELET VARCHAR(30)
    );
    


--2. 데이터 삭제
DELETE ENROLMENT;

--3. 테이블 삭제
DROP TABLE ENROLMENT;

--4. 데이터 넣기
INSERT INTO ENROLMENT(JAVA,ORACLE,JSP,SERVELET) VALUES('25','28','30','27');

--5. 데이터 수정
UPDATE ENROLMENT SET ORACLE = '30';

--6. 테이블 가져오기
SELECT * FROM ENROLMENT;