-- JOIN
--ANSI 표준, ORACLE 전용 조인 쿼리
DESC EMP;
DESC DEPT;
-- EQUI JOIN
-- NON-EQUL JOIN 

-- INNER JOIN
-- OUTER JOIN
--      LEFT OUTER JOIN
--      RIGHT OUTER JOIN
--      FULL OUTER JOIN
-- CROSS JOIN
-- SELF JOIN

SELECT * 
FROM EMP;

SELECT * 
FROM DEPT;

-- EMP 랑 DEPT를 하나로 합치기(DEPTNO 를 이용해서)
SELECT *
FROM EMP E
INNER JOIN DEPT D  --INNER 생략 가능
ON E.DEPTNO = D.DEPTNO
;

-- 위의 쿼리를 ORALCLE 전용 JOIN문으로 수정
SELECT *
FROM EMP E, DEPT D 
WHERE E.DEPTNO = D.DEPTNO
; 

-- OUTER JOIN TEST를 위해 더미 데이터 입력
INSERT INTO EMP (EMPNO, ENAME, DEPTNO) VALUES (7777, 'SWY', 50);
INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES(99, '부서부서', '역삼');
COMMIT;

-- OUTER JOIN (LEFT)
SELECT * 
FROM EMP E 
LEFT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
;

--OUTER JOIN (RIGHT)
SELECT *
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
;

--OUTER JOIN(FULL)
SELECT *
FROM EMP E
FULL OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
;

--CROSS JOIN (15x5 = 75)
SELECT *
FROM EMP E
CROSS JOIN DEPT D
;

--SELF JOIN (자기 자신을 한번 더 조인해줌)
SELECT *
FROM EMP E
INNER JOIN EMP E2
ON E.MGR = E2.EMPNO
;