DROP TABLE MEMBER;

CREATE TABLE MEMBER(
     NO NUMBER PRIMARY KEY
    , ID VARCHAR2(30) NOT NULL UNIQUE
    , PWD VARCHAR2(100) NOT NULL
    , NICK VARCHAR2(30)
    , PHONE VARCHAR2(11) 
    , GENDER CHAR(1) CHECK(GENDER IN('M','F'))
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
    , QUIT_YN CHAR(1) DEFAULT  'N' CHECK(QUIT_YN IN('Y','N')) 
);

CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
--DROP SEQUENCE SEQ_MEMEER_NO;

SELECT * FROM MEMBER;