-- UNION : 컬럼 타입 (숫자끼리, 문자끼리만 유니온 가능), 갯수 일치해야함
-- 결과 집합을 연결해줌(세로 형태로)

SELECT 10 첫번째칼럼, 20 두번째칼럼 FROM DUAL
UNION
SELECT 50 FIRSTCOL, 60 SECONDCOL FROM DUAL
UNION
SELECT 504534 FIRSTCOL, 6053 SECONDCOL FROM DUAL;


SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION
SELECT 999, '유재석' FROM DUAL;

-- INTERSECT
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
INTERSECT
SELECT 7777, 'SWY' FROM DUAL;

-- UNION ALL (중복도 전부 다 보여줌)
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION ALL
SELECT 7777, 'SWY' FROM DUAL;

SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
UNION 
SELECT 7777, 'SWY' FROM DUAL;
 
-- MINUS : A 집합에서 B 집합과 교집합인 ROW를 뺌
SELECT EMPNO 사원번호, ENAME 사원명 FROM EMP
MINUS
SELECT 7777, 'SWY' FROM DUAL;