-- 미니프로젝트 SQL

-------------
-- MEMBER TABBLE
-------------
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
      NO NUMBER PRIMARY KEY
    , ID VARCHAR2(30) NOT NULL UNIQUE
    , PWD VARCHAR(100) NOT NULL
    , NICK VARCHAR2(30) NOT NULL UNIQUE
    , ENROLL_DATE TIMESTAMP DEFAULT SYSDATE
    , QUIT_YN CHAR(1) DEFAULT 'N' CHECK(QUIT_YN IN ('Y','N'))
);

CREATE SEQUENCE MEMBER_NO_SEQ NOCACHE NOCYCLE ;
DROP SEQUENCE MEMBER_NO_SEQ;

SELECT * FROM MEMBER;

INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(1, 'USER01', '1234', 'USER01N');
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(2, 'USER02', '1234', 'USER02N');
INSERT INTO MEMBER(NO, ID, PWD, NICK) VALUES(3, 'USER03', '1234', 'USER03N');
COMMIT;


-------------
-- BOARD TABLE
-------------

CREATE TABLE BOARD(
      NO NUMBER PRIMARY KEY
    , TITLE VARCHAR(100)
    , CONTENT VARCHAR2(4000)
    , WRITER_NO NUMBER --MEMBER 테이블의 회원번호
    , REGISTER_DATE TIMESTAMP
    , DELETE_YN CHAR(1) CHECK(DELETE_YN IN ('Y','N'))
);

CREATE SEQUENCE BOARD_NO_SEQ NOCACHE NOCYCLE;
SELECT * FROM BOARD;