-- 순위 (시험 나옴 !!)

SELECT ROWNUM, E.*
FROM EMP E 
ORDER BY HIREDATE
; --이렇게 하면 ROWNUM이 뒤죽박죽 되니까 밑과 같은 쿼리로 작성해야한다.

SELECT ROW_NUMBER() OVER(ORDER BY HIREDATE) AS RN, E.* 
FROM EMP E
;

SELECT RANK() OVER(ORDER BY HIREDATE) , EMP.*
FROM EMP 
; --중복 떄문에 밀려서 10등이 안 나옴

SELECT DENSE_RANK() OVER(ORDER BY HIREDATE) , EMP.*
FROM EMP 
; --10등이 나옴

-- 그룹 나눠서 랭킹
SELECT RANK() OVER(PARTITION BY DEPTNO ORDER BY HIREDATE DESC) , EMP.*
FROM EMP 
; --PARTITION BY는 