-- 함수 (날짜)

/*
    SYSDATE
    SYSTIMESTAMP
    CURRENT_SYSTIMESTAMP
    CURRENT_DATE
*/

SELECT CURRENT_DATE
FROM DUAL;

-- EXTRACT : 추출
-- YEAR, MONTH, DAY, HOUR, MINUTE, SECOND
SELECT 
    EXTRACT(DAY FROM SYSTIMESTAMP)
,   EXTRACT(MONTH FROM SYSTIMESTAMP)
FROM DUAL;

-- NEXT_DAY : 가장 가까운 다음 날짜 (요일 지정)
SELECT NEXT_DAY(SYSDATE, '월')
FROM DUAL;

-- 가장 많이 사용 !!!! TO DATE : 날짜로 변환
SELECT TO_DATE ('2000/5/19')
FROM DUAL;


SELECT TO_CHAR(SYSDATE, 'YYYY"년"MM"월"DD"일"' ) FROM DUAL;



-- BETWEEN
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2021/05/19')) "
FROM DUAL;



SELECT MONTHS_BETWEEN(TO_DATE('1999/05/21'), TO_DATE((SELECT HIREDATE FROM EMP WHERE ENAME ='SMITH'))) "근무개월" FROM DUAL;

-- LAST_DAY
SELECT LAST_DAY(TO_DATE('2022/12/13'))
FROM DUAL;

-- ROUND 
SELECT ROUND(SYSDATE, 'YEAR')
FROM DUAL;

SELECT ROUND(SYSDATE, 'MONTH')
FROM DUAL;

-- TRUNC
SELECT TRUNC(TO_DATE('22/12/31'), 'MONTH')
FROM DUAL;